# Generated by Django 6.0.6 on 2026-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
    ]
